apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prenginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation # use only if we want prenginx to be redeployed everytime nginx is deployed
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 15.9.0 # Check latest version
    helm:
      values: |
        service:
          type: ClusterIP
        replicaCount: 2
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
  destination:
    server: https://kubernetes.default.svc
    namespace: web-apps
  syncPolicy:
    automated:
      prune: true # Automatically delete resources no longer defined in Git
      selfHeal: true # Automatically sync if live state deviates from Git-defined state
    syncOptions:
      - CreateNamespace=true # Automatically create the destination namespace if it doesn't exist
